package com.mamba.picme.core.designsystem

// ⚠️ GENERATED by scripts/gen-design-tokens.py — 勿手改；改 token 请改 design-tokens.json 后重跑生成器
// SSOT: shared/src/commonMain/resources/design-tokens.json

import androidx.compose.ui.graphics.Color

// ── M3 baseline 配色（colorScheme.light/dark）──────────────────────────────────
// 注：ErrorLight 已按 SSOT 修正为 M3 标准 #B3261E（旧值 0xB32610 有 alpha=00 透明 bug）。

val PrimaryLight = Color(0xFF1F5C54)
val OnPrimaryLight = Color.White
val PrimaryContainerLight = Color(0xFFA8D5CC)
val OnPrimaryContainerLight = Color(0xFF0A2E29)
val SecondaryLight = Color(0xFF4C635D)
val OnSecondaryLight = Color.White
val SecondaryContainerLight = Color(0xFFCEDDD7)
val OnSecondaryContainerLight = Color(0xFF0F241F)
val TertiaryLight = Color(0xFF175E4C)
val OnTertiaryLight = Color.White
val TertiaryContainerLight = Color(0xFFB4EFD8)
val OnTertiaryContainerLight = Color(0xFF002016)
val ErrorLight = Color(0xFFB3261E)
val OnErrorLight = Color.White
val ErrorContainerLight = Color(0xFFF9DEDC)
val OnErrorContainerLight = Color(0xFF410E0B)
val BackgroundLight = Color(0xFFF0EEE9)
val OnBackgroundLight = Color(0xFF1D1A16)
val SurfaceLight = Color(0xFFF0EEE9)
val OnSurfaceLight = Color(0xFF1D1A16)
val SurfaceVariantLight = Color(0xFFE4DFD6)
val OnSurfaceVariantLight = Color(0xFF4A453E)
val OutlineLight = Color(0xFF7A756D)
val OutlineVariantLight = Color(0xFFCDC7BC)
val SurfaceContainerLowestLight = Color(0xFFFBF9F5)
val SurfaceContainerLowLight = Color(0xFFF4F1EA)
val SurfaceContainerLight = Color(0xFFEFEBE3)
val SurfaceContainerHighLight = Color(0xFFE9E4DB)
val SurfaceContainerHighestLight = Color(0xFFE3DDD3)

val PrimaryDark = Color(0xFF8FD6C6)
val OnPrimaryDark = Color(0xFF003730)
val PrimaryContainerDark = Color(0xFF1F5750)
val OnPrimaryContainerDark = Color(0xFFABF0E0)
val SecondaryDark = Color(0xFFB2CCC4)
val OnSecondaryDark = Color(0xFF1D352F)
val SecondaryContainerDark = Color(0xFF344B44)
val OnSecondaryContainerDark = Color(0xFFCDE8DF)
val TertiaryDark = Color(0xFF98D5B8)
val OnTertiaryDark = Color(0xFF0A3826)
val TertiaryContainerDark = Color(0xFF25523D)
val OnTertiaryContainerDark = Color(0xFFB3F1D2)
val ErrorDark = Color(0xFFF2B8B5)
val OnErrorDark = Color(0xFF601410)
val ErrorContainerDark = Color(0xFF8C1D18)
val OnErrorContainerDark = Color(0xFFF9DEDC)
val BackgroundDark = Color(0xFF171412)
val OnBackgroundDark = Color(0xFFEDE9E3)
val SurfaceDark = Color(0xFF171412)
val OnSurfaceDark = Color(0xFFEDE9E3)
val SurfaceVariantDark = Color(0xFF46413A)
val OnSurfaceVariantDark = Color(0xFFCFC9BF)
val OutlineDark = Color(0xFF968F86)
val OutlineVariantDark = Color(0xFF46413A)
val SurfaceContainerLowestDark = Color(0xFF100E0C)
val SurfaceContainerLowDark = Color(0xFF1B1815)
val SurfaceContainerDark = Color(0xFF211E1A)
val SurfaceContainerHighDark = Color(0xFF2B2722)
val SurfaceContainerHighestDark = Color(0xFF36312B)

// ── 功能色（color 组，不随主题切换）。引用方式：MaterialTheme.appColors.focusRing ──────────
val FocusRingColor = Color(0xFF00E5FF)
val PanelBackgroundColor = Color(0xCC000000)
val ShutterRingColor = Color(0xFFE4E4E4)
val SliderThumbColor = Color.White
val VibrantGreen = Color(0xFF00E676)
val VibrantBlue = Color(0xFF2979FF)
val VibrantOrange = Color(0xFFFF9100)
val VibrantPink = Color(0xFFFF4081)
val VibrantPurple = Color(0xFF4F378B)

/** 功能色集合，通过 [MaterialTheme.appColors] 访问。 */
object AppColors {
    val focusRing = FocusRingColor
    val panelBackground = PanelBackgroundColor
    val shutterRing = ShutterRingColor
    val sliderThumb = SliderThumbColor
    val vibrantGreen = VibrantGreen
    val vibrantBlue = VibrantBlue
    val vibrantOrange = VibrantOrange
    val vibrantPink = VibrantPink
    val vibrantPurple = VibrantPurple
}
