package com.mamba.picme.core.designsystem

// ⚠️ GENERATED by scripts/gen-design-tokens.py — 勿手改；改 token 请改 design-tokens.json 后重跑生成器
// SSOT: shared/src/commonMain/resources/design-tokens.json

import androidx.compose.ui.graphics.Color

// ── M3 baseline 配色（colorScheme.light/dark）──────────────────────────────────
// 注：ErrorLight 已按 SSOT 修正为 M3 标准 #B3261E（旧值 0xB32610 有 alpha=00 透明 bug）。

val PrimaryLight = Color(0xFF6750A4)
val OnPrimaryLight = Color.White
val PrimaryContainerLight = Color(0xFFEADDFF)
val OnPrimaryContainerLight = Color(0xFF21005D)
val SecondaryLight = Color(0xFF625B71)
val OnSecondaryLight = Color.White
val SecondaryContainerLight = Color(0xFFE8DEF8)
val OnSecondaryContainerLight = Color(0xFF1D192B)
val TertiaryLight = Color(0xFF7D5260)
val OnTertiaryLight = Color.White
val TertiaryContainerLight = Color(0xFFFFD8E4)
val OnTertiaryContainerLight = Color(0xFF31111D)
val ErrorLight = Color(0xFFB3261E)
val OnErrorLight = Color.White
val ErrorContainerLight = Color(0xFFF9DEDC)
val OnErrorContainerLight = Color(0xFF410E0B)
val BackgroundLight = Color(0xFFFFFBFE)
val OnBackgroundLight = Color(0xFF1C1B1F)
val SurfaceLight = Color(0xFFFFFBFE)
val OnSurfaceLight = Color(0xFF1C1B1F)
val SurfaceVariantLight = Color(0xFFE7E0EC)
val OnSurfaceVariantLight = Color(0xFF49454F)
val OutlineLight = Color(0xFF79747E)
val OutlineVariantLight = Color(0xFFCAC4D0)
val SurfaceContainerLowestLight = Color.White
val SurfaceContainerLowLight = Color(0xFFF7F2FA)
val SurfaceContainerLight = Color(0xFFF3EDF7)
val SurfaceContainerHighLight = Color(0xFFEDE7F0)
val SurfaceContainerHighestLight = Color(0xFFE6E0E9)

val PrimaryDark = Color(0xFFD0BCFF)
val OnPrimaryDark = Color(0xFF381E72)
val PrimaryContainerDark = Color(0xFF4F378B)
val OnPrimaryContainerDark = Color(0xFFEADDFF)
val SecondaryDark = Color(0xFFCCC2DC)
val OnSecondaryDark = Color(0xFF332D41)
val SecondaryContainerDark = Color(0xFF4A4458)
val OnSecondaryContainerDark = Color(0xFFE8DEF8)
val TertiaryDark = Color(0xFFEFB8C8)
val OnTertiaryDark = Color(0xFF492532)
val TertiaryContainerDark = Color(0xFF633B48)
val OnTertiaryContainerDark = Color(0xFFFFD8E4)
val ErrorDark = Color(0xFFF2B8B5)
val OnErrorDark = Color(0xFF601410)
val ErrorContainerDark = Color(0xFF8C1D18)
val OnErrorContainerDark = Color(0xFFF9DEDC)
val BackgroundDark = Color(0xFF1C1B1F)
val OnBackgroundDark = Color(0xFFE6E1E5)
val SurfaceDark = Color(0xFF1C1B1F)
val OnSurfaceDark = Color(0xFFE6E1E5)
val SurfaceVariantDark = Color(0xFF49454F)
val OnSurfaceVariantDark = Color(0xFFCAC4D0)
val OutlineDark = Color(0xFF938F99)
val OutlineVariantDark = Color(0xFF49454F)
val SurfaceContainerLowestDark = Color(0xFF0F0D13)
val SurfaceContainerLowDark = Color(0xFF1D1B20)
val SurfaceContainerDark = Color(0xFF211F26)
val SurfaceContainerHighDark = Color(0xFF2B2930)
val SurfaceContainerHighestDark = Color(0xFF36343B)

// ── 功能色（color 组，不随主题切换）。引用方式：MaterialTheme.appColors.focusRing ──────────
val FocusRingColor = Color(0xFF00E5FF)
val PanelBackgroundColor = Color(0xCC000000)
val ShutterRingColor = Color.White
val SliderThumbColor = Color.White
val VibrantGreen = Color(0xFF00E676)
val VibrantBlue = Color(0xFF2979FF)
val VibrantOrange = Color(0xFFFF9100)
val VibrantPink = Color(0xFFFF4081)

/** 功能色集合，通过 [MaterialTheme.appColors] 访问。 */
object AppColors {
    val focusRing = FocusRingColor
    val panelBackground = PanelBackgroundColor
    val shutterRing = ShutterRingColor
    val sliderThumb = SliderThumbColor
    val vibrantGreen = VibrantGreen
    val vibrantBlue = VibrantBlue
    val vibrantOrange = VibrantOrange
    val vibrantPink = VibrantPink
}
