package com.mamba.picme.core.designsystem

// ⚠️ GENERATED by scripts/gen-design-tokens.py — 勿手改；改 token 请改 design-tokens.json 后重跑生成器
// SSOT: shared/src/commonMain/resources/design-tokens.json

import androidx.compose.ui.unit.dp

/** 全局间距令牌。引用方式：`MaterialTheme.spacing.sm` 或直接 `Spacing.sm`。 */
object Spacing {
    val xs = 4.dp
    val sm = 8.dp
    val md = 12.dp
    val lg = 16.dp
    val xl = 24.dp
    val xxl = 32.dp
}
