package com.mamba.picme.features.gallery.components

import java.util.Locale

/**
 * 格言数据结构，含正文与作者/出处。
 */
data class GalleryQuote(
    val text: String,
    val author: String
)

/**
 * 中文格言池 — 涵盖古诗词、近现代名言、哲学思想、生活感悟。
 */
val chineseQuotes: List<GalleryQuote> = listOf(
    // ── 古典诗词 ──
    GalleryQuote("长风破浪会有时，直挂云帆济沧海。", "李白《行路难》"),
    GalleryQuote("会当凌绝顶，一览众山小。", "杜甫《望岳》"),
    GalleryQuote("海内存知己，天涯若比邻。", "王勃《送杜少府之任蜀州》"),
    GalleryQuote("莫愁前路无知己，天下谁人不识君。", "高适《别董大》"),
    GalleryQuote("天生我材必有用，千金散尽还复来。", "李白《将进酒》"),
    GalleryQuote("大江东去，浪淘尽，千古风流人物。", "苏轼《念奴娇·赤壁怀古》"),
    GalleryQuote("竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。", "苏轼《定风波》"),
    GalleryQuote("但愿人长久，千里共婵娟。", "苏轼《水调歌头》"),
    GalleryQuote("人生自古谁无死？留取丹心照汗青。", "文天祥《过零丁洋》"),
    GalleryQuote("沉舟侧畔千帆过，病树前头万木春。", "刘禹锡《酬乐天扬州初逢席上见赠》"),
    GalleryQuote("山重水复疑无路，柳暗花明又一村。", "陆游《游山西村》"),
    GalleryQuote("纸上得来终觉浅，绝知此事要躬行。", "陆游《冬夜读书示子聿》"),
    GalleryQuote("千磨万击还坚劲，任尔东西南北风。", "郑燮《竹石》"),
    GalleryQuote("落红不是无情物，化作春泥更护花。", "龚自珍《己亥杂诗》"),
    GalleryQuote("不畏浮云遮望眼，自缘身在最高层。", "王安石《登飞来峰》"),
    GalleryQuote("会挽雕弓如满月，西北望，射天狼。", "苏轼《江城子·密州出猎》"),
    GalleryQuote("采菊东篱下，悠然见南山。", "陶渊明《饮酒》"),
    GalleryQuote("海上生明月，天涯共此时。", "张九龄《望月怀远》"),
    GalleryQuote("春风又绿江南岸，明月何时照我还。", "王安石《泊船瓜洲》"),
    GalleryQuote("接天莲叶无穷碧，映日荷花别样红。", "杨万里《晓出净慈寺送林子方》"),
    GalleryQuote("人生得意须尽欢，莫使金樽空对月。", "李白《将进酒》"),
    GalleryQuote("路漫漫其修远兮，吾将上下而求索。", "屈原《离骚》"),
    GalleryQuote("亦余心之所善兮，虽九死其犹未悔。", "屈原《离骚》"),
    GalleryQuote("天行健，君子以自强不息。", "《周易·乾卦》"),
    GalleryQuote("地势坤，君子以厚德载物。", "《周易·坤卦》"),
    GalleryQuote("不积跬步，无以至千里；不积小流，无以成江海。", "荀子《劝学》"),
    GalleryQuote("锲而舍之，朽木不折；锲而不舍，金石可镂。", "荀子《劝学》"),
    GalleryQuote("三人行，必有我师焉。", "《论语·述而》"),
    GalleryQuote("学而不思则罔，思而不学则殆。", "《论语·为政》"),
    GalleryQuote("知之者不如好之者，好之者不如乐之者。", "《论语·雍也》"),
    GalleryQuote("己所不欲，勿施于人。", "《论语·卫灵公》"),
    GalleryQuote("君子坦荡荡，小人长戚戚。", "《论语·述而》"),
    GalleryQuote("温故而知新，可以为师矣。", "《论语·为政》"),
    GalleryQuote("敏而好学，不耻下问。", "《论语·公冶长》"),
    GalleryQuote("言必信，行必果。", "《论语·子路》"),
    GalleryQuote("富润屋，德润身，心广体胖。", "《大学》"),
    GalleryQuote("上善若水。水善利万物而不争。", "老子《道德经》"),
    GalleryQuote("千里之行，始于足下。", "老子《道德经》"),
    GalleryQuote("祸兮福之所倚，福兮祸之所伏。", "老子《道德经》"),
    GalleryQuote("合抱之木，生于毫末；九层之台，起于累土。", "老子《道德经》"),
    GalleryQuote("天下难事，必作于易；天下大事，必作于细。", "老子《道德经》"),
    GalleryQuote("知人者智，自知者明。", "老子《道德经》"),
    GalleryQuote("大方无隅，大器晚成，大音希声，大象无形。", "老子《道德经》"),
    GalleryQuote("吾生也有涯，而知也无涯。", "庄子《养生主》"),
    GalleryQuote("独与天地精神往来。", "庄子《天下》"),
    GalleryQuote("天地有大美而不言。", "庄子《知北游》"),
    GalleryQuote("朴素而天下莫能与之争美。", "庄子《天道》"),

    // ── 近现代名言 ──
    GalleryQuote("世界上本没有路，走的人多了，也便成了路。", "鲁迅《故乡》"),
    GalleryQuote("希望是本无所谓有，无所谓无的。", "鲁迅《故乡》"),
    GalleryQuote("横眉冷对千夫指，俯首甘为孺子牛。", "鲁迅《自嘲》"),
    GalleryQuote("时间就像海绵里的水，只要愿挤，总还是有的。", "鲁迅"),
    GalleryQuote("不在沉默中爆发，就在沉默中灭亡。", "鲁迅《记念刘和珍君》"),
    GalleryQuote("面朝大海，春暖花开。", "海子《面朝大海，春暖花开》"),
    GalleryQuote("从明天起，做一个幸福的人。", "海子"),
    GalleryQuote("黑夜给了我黑色的眼睛，我却用它寻找光明。", "顾城《一代人》"),
    GalleryQuote("生活不止眼前的苟且，还有诗和远方。", "高晓松"),
    GalleryQuote("愿你走出半生，归来仍是少年。", "佚名"),
    GalleryQuote("心若没有栖息的地方，到哪里都是流浪。", "三毛"),
    GalleryQuote("每想你一次，天上飘落一粒沙，从此形成了撒哈拉。", "三毛"),
    GalleryQuote("梦想，可以天花乱坠；理想，是我们一步一个脚印踩出来的坎坷道路。", "三毛"),
    GalleryQuote("我来不及认真地年轻，待明白过来时，只能选择认真地老去。", "三毛"),
    GalleryQuote("人间不会有单纯的快乐，快乐总夹带着烦恼和忧虑。", "杨绛《我们仨》"),
    GalleryQuote("我们曾如此期盼外界的认可，到最后才知道，世界是自己的，与他人毫无关系。", "杨绛"),
    GalleryQuote("你的问题主要在于读书不多而想得太多。", "杨绛"),
    GalleryQuote("我和谁都不争，和谁争我都不屑。", "杨绛（译兰德诗）"),
    GalleryQuote("一个人经过不同程度的锻炼，就获得不同程度的修养、不同程度的效益。", "杨绛"),
    GalleryQuote("人生没有彩排，每天都是现场直播。", "佚名"),
    GalleryQuote("你若盛开，清风自来。心若浮沉，浅笑安然。", "佚名"),
    GalleryQuote("去爱吧，像不曾受过一次伤一样；跳舞吧，像没有人欣赏一样。", "佚名"),
    GalleryQuote("走自己的路，让别人说去吧。", "但丁"),
    GalleryQuote("不要因为走得太远，而忘记为什么出发。", "纪伯伦"),
    GalleryQuote("心有猛虎，细嗅蔷薇。", "萨松（余光中译）"),
    GalleryQuote("岁月不饶人，我亦未曾饶过岁月。", "木心"),
    GalleryQuote("从前的日色变得慢，车、马、邮件都慢，一生只够爱一个人。", "木心《从前慢》"),
    GalleryQuote("无知的人是没有灵魂的。", "木心"),
    GalleryQuote("所谓无底深渊，下去，也是前程万里。", "木心"),
    GalleryQuote("生命好在无意义，才容得下各自赋予意义。", "木心"),
    GalleryQuote("真正的平静，不是避开车马喧嚣，而是在心中修篱种菊。", "佚名"),
    GalleryQuote("你是一树一树的花开，是燕在梁间呢喃。", "林徽因《你是人间的四月天》"),
    GalleryQuote("温柔要有，但不是妥协，我们要在安静中，不慌不忙地坚强。", "佚名"),
    GalleryQuote("如果有来生，要做一棵树，站成永恒，没有悲欢的姿势。", "三毛"),
    GalleryQuote("我行过许多地方的桥，看过许多次数的云，喝过许多种类的酒，却只爱过一个正当最好年龄的人。", "沈从文"),
    GalleryQuote("凡事都有偶然的凑巧，结果却又如宿命的必然。", "沈从文"),
    GalleryQuote("我明白你会来，所以我等。", "沈从文"),
    GalleryQuote("人生就是一列开往坟墓的列车，路途上会有很多站。", "佚名"),
    GalleryQuote("每一个不曾起舞的日子，都是对生命的辜负。", "尼采"),
    GalleryQuote("当你凝视深渊时，深渊也在凝视你。", "尼采"),
    GalleryQuote("那些杀不死我的，使我更强大。", "尼采"),
    GalleryQuote("其实人跟树是一样的，越是向往高处的阳光，根就越要伸向黑暗的地底。", "尼采"),
    GalleryQuote("白昼之光，岂知夜色之深。", "尼采"),
    GalleryQuote("一个人知道自己为什么而活，就可以忍受任何一种生活。", "尼采"),

    // ── 生活哲理 ──
    GalleryQuote("种一棵树最好的时间是十年前，其次是现在。", "佚名"),
    GalleryQuote("你的孤独，虽败犹荣。", "刘同"),
    GalleryQuote("生命的意义不在于活了多少日子，而在于有多少日子值得记住。", "佚名"),
    GalleryQuote("人生没有白走的路，每一步都算数。", "李宗盛"),
    GalleryQuote("所有命运赠送的礼物，早已在暗中标好了价格。", "茨威格"),
    GalleryQuote("这个世界上只有一种英雄主义，那就是在认清生活的真相后依然热爱生活。", "罗曼·罗兰"),
    GalleryQuote("大部分人在二三十岁时就死去了，过了这个年龄，他们只是自己的影子。", "罗曼·罗兰"),
    GalleryQuote("幸福的家庭都是相似的，不幸的家庭各有各的不幸。", "托尔斯泰"),
    GalleryQuote("我们最重要的不是去计较真与伪、得与失、名与利、贵与贱、富与贫，而是如何好好地快乐度日。", "杨绛"),
    GalleryQuote("人间值得。", "中村恒子"),
    GalleryQuote("万物皆有裂痕，那是光照进来的地方。", "莱昂纳德·科恩"),
    GalleryQuote("生活总是让我们遍体鳞伤，但到后来，那些受伤的地方一定会变成我们最强壮的地方。", "海明威"),
    GalleryQuote("一个人可以被毁灭，但不能被打败。", "海明威《老人与海》"),
    GalleryQuote("优于别人，并不高贵，真正的高贵应该是优于过去的自己。", "海明威"),
    GalleryQuote("向死而生。", "海德格尔"),
    GalleryQuote("凡是过往，皆为序章。", "莎士比亚《暴风雨》"),
    GalleryQuote("做你自己，因为别人都有人做了。", "王尔德"),
    GalleryQuote("我们都生活在阴沟里，但仍有人仰望星空。", "王尔德"),
    GalleryQuote("爱自己是终身浪漫的开始。", "王尔德"),
    GalleryQuote("人生有两个悲剧，第一是想得到的得不到，第二是想得到的得到了。", "王尔德"),
    GalleryQuote("你若咬了人，就别怪人咬你。", "佚名"),
    GalleryQuote("时间是一切财富中最宝贵的财富。", "德奥弗拉斯多"),
    GalleryQuote("把每一天当作生命的最后一天来过。", "佚名"),
    GalleryQuote("不要温和地走进那个良夜。", "狄兰·托马斯"),
    GalleryQuote("怒发冲冠，凭栏处、潇潇雨歇。抬望眼，仰天长啸，壮怀激烈。", "岳飞《满江红》"),
    GalleryQuote("谁终将声震人间，必长久深自缄默；谁终将点燃闪电，必长久如云漂泊。", "尼采"),
    GalleryQuote("我所拥有的金钱是为了换取自由的工具，而非奴役我的枷锁。", "卢梭"),
    GalleryQuote("人生而自由，却无往不在枷锁之中。", "卢梭"),
    GalleryQuote("一个人需要知道他所受到的限制，以及他所能达到的高度。", "佚名"),
    GalleryQuote("我们一路奔走，只为找回自己。", "佚名"),
    GalleryQuote("人的一切痛苦，本质上都是对自己无能的愤怒。", "王小波"),
    GalleryQuote("一个人只有在独处时才能成为自己。", "叔本华"),
    GalleryQuote("要么庸俗，要么孤独。", "叔本华"),
    GalleryQuote("人性一个最特别的弱点就是：在意别人如何看待自己。", "叔本华"),
    GalleryQuote("生命是一团欲望，欲望不满足便痛苦，满足便无聊。", "叔本华"),
    GalleryQuote("所有的光鲜亮丽，都需要付出代价。", "佚名"),
    GalleryQuote("在哪里跌倒，就在哪里躺一会儿。", "佚名"),
    GalleryQuote("愿你历尽千帆，归来仍是少年。", "佚名"),
    GalleryQuote("每一个优秀的人，都有一段沉默的时光。", "佚名"),
    GalleryQuote("不乱于心，不困于情；不畏将来，不念过往。如此，安好。", "丰子恺"),
    GalleryQuote("既然无处可逃，不如喜悦；既然没有净土，不如静心。", "丰子恺"),
    GalleryQuote("心小了，所有的小事就大了；心大了，所有的大事都小了。", "丰子恺"),
    GalleryQuote("你若爱，生活哪里都可爱；你若恨，生活哪里都可恨。", "丰子恺"),
    GalleryQuote("人就这么一辈子，一晃就过完了，不要亏待每一份热情。", "佚名"),
    GalleryQuote("好看的皮囊千篇一律，有趣的灵魂万里挑一。", "佚名"),
    GalleryQuote("这世上只有一种成功，就是能够用自己喜欢的方式度过自己的一生。", "佚名"),
    GalleryQuote("你的气质里，藏着你走过的路、读过的书和爱过的人。", "佚名"),
    GalleryQuote("一切都将会过去，而过去了的，就会成为亲切的怀恋。", "普希金"),
    GalleryQuote("假如生活欺骗了你，不要悲伤，不要心急。", "普希金"),
    GalleryQuote("世界以痛吻我，要我报之以歌。", "泰戈尔"),
    GalleryQuote("生如夏花之绚烂，死如秋叶之静美。", "泰戈尔《飞鸟集》"),
    GalleryQuote("我们把世界看错，反说它欺骗了我们。", "泰戈尔《飞鸟集》"),
    GalleryQuote("如果你因失去了太阳而流泪，那么你也失去了群星。", "泰戈尔《飞鸟集》"),
    GalleryQuote("天空没留下翅膀的痕迹，但我已飞过。", "泰戈尔"),
    GalleryQuote("纵浪大化中，不喜亦不惧。应尽便须尽，无复独多虑。", "陶渊明"),
    GalleryQuote("回首向来萧瑟处，归去，也无风雨也无晴。", "苏轼《定风波》"),
    GalleryQuote("宠辱不惊，闲看庭前花开花落；去留无意，漫随天外云卷云舒。", "《菜根谭》"),
    GalleryQuote("心静自然凉。", "白居易"),
    GalleryQuote("今日事，今日毕。", "曾国藩"),
    GalleryQuote("莫问收获，但问耕耘。", "曾国藩"),
    GalleryQuote("物来顺应，未来不迎，当时不杂，既过不恋。", "曾国藩"),
    GalleryQuote("天下事有所激有所逼而成者居其半。", "曾国藩"),
    GalleryQuote("士人第一要志气，第二要识量，三须才干。", "曾国藩"),

    // ── 摄影与艺术 ──
    GalleryQuote("每一张照片，都是时光的标本。", "佚名"),
    GalleryQuote("摄影是用光作画的艺术。", "佚名"),
    GalleryQuote("最好的相机，是你眼中的世界。", "佚名"),
    GalleryQuote("摄影是光与影的诗歌。", "佚名"),
    GalleryQuote("照片是生活的暂停键。", "佚名"),
    GalleryQuote("捕捉瞬间，珍藏永恒。", "佚名"),
    GalleryQuote("生活不是缺少美，而是缺少发现美的眼睛。", "罗丹"),
    GalleryQuote("艺术来源于生活，又高于生活。", "车尔尼雪夫斯基"),
    GalleryQuote("美到处都有，对于我们的眼睛，不是缺少美，而是缺少发现。", "罗丹"),
    GalleryQuote("生活中最伟大的事情不在于我们站在哪里，而在于我们朝什么方向移动。", "霍姆斯")
)

/**
 * 英文格言池 — 涵盖文学经典、哲学思想、科学人文、生活智慧。
 */
val englishQuotes: List<GalleryQuote> = listOf(
    // ── Literature & Poetry ──
    GalleryQuote("Whatever you are, be a good one.", "Abraham Lincoln"),
    GalleryQuote("The only way to do great work is to love what you do.", "Steve Jobs"),
    GalleryQuote("Stay hungry, stay foolish.", "Steve Jobs"),
    GalleryQuote("In the middle of difficulty lies opportunity.", "Albert Einstein"),
    GalleryQuote("Imagination is more important than knowledge.", "Albert Einstein"),
    GalleryQuote("Life is like riding a bicycle. To keep your balance, you must keep moving.", "Albert Einstein"),
    GalleryQuote("Try not to become a man of success, but rather try to become a man of value.", "Albert Einstein"),
    GalleryQuote("The important thing is not to stop questioning.", "Albert Einstein"),
    GalleryQuote("Anyone who has never made a mistake has never tried anything new.", "Albert Einstein"),
    GalleryQuote("Look deep into nature, and then you will understand everything better.", "Albert Einstein"),
    GalleryQuote("Two roads diverged in a wood, and I took the one less traveled by.", "Robert Frost"),
    GalleryQuote("The best way out is always through.", "Robert Frost"),
    GalleryQuote("In three words I can sum up everything I've learned about life: it goes on.", "Robert Frost"),
    GalleryQuote("Hope is the thing with feathers that perches in the soul.", "Emily Dickinson"),
    GalleryQuote("To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "Ralph Waldo Emerson"),
    GalleryQuote("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
    GalleryQuote("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"),
    GalleryQuote("Nothing great was ever achieved without enthusiasm.", "Ralph Waldo Emerson"),
    GalleryQuote("The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"),
    GalleryQuote("To be, or not to be, that is the question.", "William Shakespeare"),
    GalleryQuote("This above all: to thine own self be true.", "William Shakespeare"),
    GalleryQuote("We know what we are, but know not what we may be.", "William Shakespeare"),
    GalleryQuote("All the world's a stage, and all the men and women merely players.", "William Shakespeare"),
    GalleryQuote("It is not in the stars to hold our destiny but in ourselves.", "William Shakespeare"),
    GalleryQuote("Some are born great, some achieve greatness, and some have greatness thrust upon them.", "William Shakespeare"),
    GalleryQuote("The fool doth think he is wise, but the wise man knows himself to be a fool.", "William Shakespeare"),
    GalleryQuote("Go confidently in the direction of your dreams. Live the life you have imagined.", "Henry David Thoreau"),
    GalleryQuote("I went to the woods because I wished to live deliberately.", "Henry David Thoreau"),
    GalleryQuote("Simplify, simplify.", "Henry David Thoreau"),
    GalleryQuote("The mass of men lead lives of quiet desperation.", "Henry David Thoreau"),
    GalleryQuote("Success usually comes to those who are too busy to be looking for it.", "Henry David Thoreau"),

    // ── Philosophy & Wisdom ──
    GalleryQuote("The unexamined life is not worth living.", "Socrates"),
    GalleryQuote("I know that I know nothing.", "Socrates"),
    GalleryQuote("He who is not contented with what he has, would not be contented with what he would like to have.", "Socrates"),
    GalleryQuote("Knowing yourself is the beginning of all wisdom.", "Aristotle"),
    GalleryQuote("Happiness depends upon ourselves.", "Aristotle"),
    GalleryQuote("The roots of education are bitter, but the fruit is sweet.", "Aristotle"),
    GalleryQuote("It is the mark of an educated mind to be able to entertain a thought without accepting it.", "Aristotle"),
    GalleryQuote("We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Aristotle"),
    GalleryQuote("Man is condemned to be free.", "Jean-Paul Sartre"),
    GalleryQuote("Hell is other people.", "Jean-Paul Sartre"),
    GalleryQuote("Man is nothing else but what he makes of himself.", "Jean-Paul Sartre"),
    GalleryQuote("One must imagine Sisyphus happy.", "Albert Camus"),
    GalleryQuote("In the depth of winter, I finally learned that within me there lay an invincible summer.", "Albert Camus"),
    GalleryQuote("Real generosity toward the future lies in giving all to the present.", "Albert Camus"),
    GalleryQuote("You will never be happy if you continue to search for what happiness consists of.", "Albert Camus"),
    GalleryQuote("He who has a why to live for can bear almost any how.", "Friedrich Nietzsche"),
    GalleryQuote("And those who were seen dancing were thought to be insane by those who could not hear the music.", "Friedrich Nietzsche"),
    GalleryQuote("What does not kill me makes me stronger.", "Friedrich Nietzsche"),
    GalleryQuote("Without music, life would be a mistake.", "Friedrich Nietzsche"),
    GalleryQuote("The snake which cannot cast its skin has to die. As well the minds which are prevented from changing their opinions.", "Friedrich Nietzsche"),

    // ── Writers & Thinkers ──
    GalleryQuote("The man who does not read has no advantage over the man who cannot read.", "Mark Twain"),
    GalleryQuote("Whenever you find yourself on the side of the majority, it is time to pause and reflect.", "Mark Twain"),
    GalleryQuote("The two most important days in your life are the day you are born and the day you find out why.", "Mark Twain"),
    GalleryQuote("Kindness is the language which the deaf can hear and the blind can see.", "Mark Twain"),
    GalleryQuote("Courage is resistance to fear, mastery of fear, not absence of fear.", "Mark Twain"),
    GalleryQuote("Be yourself; everyone else is already taken.", "Oscar Wilde"),
    GalleryQuote("We are all in the gutter, but some of us are looking at stars.", "Oscar Wilde"),
    GalleryQuote("To live is the rarest thing in the world. Most people exist, that is all.", "Oscar Wilde"),
    GalleryQuote("Always forgive your enemies; nothing annoys them so much.", "Oscar Wilde"),
    GalleryQuote("Some cause happiness wherever they go; others whenever they go.", "Oscar Wilde"),
    GalleryQuote("Life is far too important a thing ever to talk seriously about.", "Oscar Wilde"),
    GalleryQuote("A man who does not think for himself does not think at all.", "Oscar Wilde"),
    GalleryQuote("The best way to find yourself is to lose yourself in the service of others.", "Mahatma Gandhi"),
    GalleryQuote("Be the change that you wish to see in the world.", "Mahatma Gandhi"),
    GalleryQuote("Live as if you were to die tomorrow. Learn as if you were to live forever.", "Mahatma Gandhi"),
    GalleryQuote("Happiness is when what you think, what you say, and what you do are in harmony.", "Mahatma Gandhi"),
    GalleryQuote("The future depends on what you do today.", "Mahatma Gandhi"),
    GalleryQuote("Darkness cannot drive out darkness; only light can do that.", "Martin Luther King Jr."),
    GalleryQuote("Injustice anywhere is a threat to justice everywhere.", "Martin Luther King Jr."),
    GalleryQuote("Faith is taking the first step even when you don't see the whole staircase.", "Martin Luther King Jr."),
    GalleryQuote("Our lives begin to end the day we become silent about things that matter.", "Martin Luther King Jr."),
    GalleryQuote("If you can dream it, you can do it.", "Walt Disney"),
    GalleryQuote("All our dreams can come true, if we have the courage to pursue them.", "Walt Disney"),
    GalleryQuote("The way to get started is to quit talking and begin doing.", "Walt Disney"),
    GalleryQuote("Whether you think you can, or you think you can't, you're right.", "Henry Ford"),
    GalleryQuote("Quality means doing it right when no one is looking.", "Henry Ford"),
    GalleryQuote("Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill"),
    GalleryQuote("Never, never, never give up.", "Winston Churchill"),
    GalleryQuote("We make a living by what we get, but we make a life by what we give.", "Winston Churchill"),
    GalleryQuote("A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.", "Winston Churchill"),
    GalleryQuote("Continuous effort, not strength or intelligence, is the key to unlocking our potential.", "Winston Churchill"),
    GalleryQuote("It is never too late to be what you might have been.", "George Eliot"),
    GalleryQuote("The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"),
    GalleryQuote("The only thing we have to fear is fear itself.", "Franklin D. Roosevelt"),
    GalleryQuote("Happiness lies in the joy of achievement and the thrill of creative effort.", "Franklin D. Roosevelt"),

    // ── Science & Innovation ──
    GalleryQuote("The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.", "Stephen Hawking"),
    GalleryQuote("Intelligence is the ability to adapt to change.", "Stephen Hawking"),
    GalleryQuote("Look up at the stars and not down at your feet.", "Stephen Hawking"),
    GalleryQuote("Nothing in life is to be feared, it is only to be understood.", "Marie Curie"),
    GalleryQuote("Life is not easy for any of us. But what of that? We must have perseverance.", "Marie Curie"),
    GalleryQuote("I was taught that the way of progress was neither swift nor easy.", "Marie Curie"),
    GalleryQuote("Somewhere, something incredible is waiting to be known.", "Carl Sagan"),
    GalleryQuote("We are made of star-stuff.", "Carl Sagan"),
    GalleryQuote("Extraordinary claims require extraordinary evidence.", "Carl Sagan"),
    GalleryQuote("The good thing about science is that it's true whether or not you believe in it.", "Neil deGrasse Tyson"),
    GalleryQuote("Creativity is intelligence having fun.", "Albert Einstein"),

    // ── Life & Inspiration ──
    GalleryQuote("The purpose of our lives is to be happy.", "Dalai Lama"),
    GalleryQuote("Happiness is not something ready made. It comes from your own actions.", "Dalai Lama"),
    GalleryQuote("If you want others to be happy, practice compassion.", "Dalai Lama"),
    GalleryQuote("Remember that sometimes not getting what you want is a wonderful stroke of luck.", "Dalai Lama"),
    GalleryQuote("Life is what happens when you're busy making other plans.", "John Lennon"),
    GalleryQuote("Imagine all the people living life in peace.", "John Lennon"),
    GalleryQuote("You may say I'm a dreamer, but I'm not the only one.", "John Lennon"),
    GalleryQuote("Time you enjoy wasting is not wasted time.", "John Lennon"),
    GalleryQuote("You miss 100% of the shots you don't take.", "Wayne Gretzky"),
    GalleryQuote("It's not whether you get knocked down, it's whether you get up.", "Vince Lombardi"),
    GalleryQuote("The only impossible journey is the one you never begin.", "Tony Robbins"),
    GalleryQuote("It always seems impossible until it's done.", "Nelson Mandela"),
    GalleryQuote("Education is the most powerful weapon which you can use to change the world.", "Nelson Mandela"),
    GalleryQuote("A winner is a dreamer who never gives up.", "Nelson Mandela"),
    GalleryQuote("I learned that courage was not the absence of fear, but the triumph over it.", "Nelson Mandela"),
    GalleryQuote("May you live every day of your life.", "Jonathan Swift"),
    GalleryQuote("The journey of a thousand miles begins with a single step.", "Lao Tzu"),
    GalleryQuote("When I let go of what I am, I become what I might be.", "Lao Tzu"),
    GalleryQuote("Nature does not hurry, yet everything is accomplished.", "Lao Tzu"),
    GalleryQuote("Mastering others is strength; mastering yourself is true power.", "Lao Tzu"),
    GalleryQuote("To know that we know what we know, and to know that we do not know what we do not know, that is true knowledge.", "Nicolaus Copernicus"),
    GalleryQuote("The mind is everything. What you think you become.", "Buddha"),
    GalleryQuote("Three things cannot be long hidden: the sun, the moon, and the truth.", "Buddha"),
    GalleryQuote("Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else; you are the one who gets burned.", "Buddha"),
    GalleryQuote("Peace comes from within. Do not seek it without.", "Buddha"),
    GalleryQuote("What we think, we become.", "Buddha"),
    GalleryQuote("The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"),
    GalleryQuote("Fall seven times and stand up eight.", "Japanese Proverb"),
    GalleryQuote("The expert in anything was once a beginner.", "Helen Hayes"),
    GalleryQuote("Life is really simple, but we insist on making it complicated.", "Confucius"),
    GalleryQuote("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    GalleryQuote("Our greatest glory is not in never falling, but in rising every time we fall.", "Confucius"),
    GalleryQuote("Everything has beauty, but not everyone sees it.", "Confucius"),
    GalleryQuote("The man who moves a mountain begins by carrying away small stones.", "Confucius"),
    GalleryQuote("When you see a good person, think of becoming like them. When you see someone not so good, reflect on your own weak points.", "Confucius"),
    GalleryQuote("By three methods we may learn wisdom: by reflection, by imitation, and by experience.", "Confucius"),

    // ── Art & Photography ──
    GalleryQuote("The best camera is the one you have with you.", "Chase Jarvis"),
    GalleryQuote("Photography is the beauty of life captured.", "Unknown"),
    GalleryQuote("You don't take a photograph, you make it.", "Ansel Adams"),
    GalleryQuote("A photograph is the pause button of life.", "Unknown"),
    GalleryQuote("Photography takes an instant out of time, altering life by holding it still.", "Dorothea Lange"),
    GalleryQuote("The camera is an instrument that teaches people how to see without a camera.", "Dorothea Lange"),
    GalleryQuote("When words become unclear, I shall focus with photographs.", "Ansel Adams"),
    GalleryQuote("There are always two people in every picture: the photographer and the viewer.", "Ansel Adams"),
    GalleryQuote("A photograph is a secret about a secret.", "Diane Arbus"),
    GalleryQuote("Taking pictures is savoring life intensely, every hundredth of a second.", "Ruth Bernhard"),
    GalleryQuote("Light makes photography. Embrace light.", "George Eastman"),
    GalleryQuote("Art is not what you see, but what you make others see.", "Edgar Degas"),
    GalleryQuote("Every artist was first an amateur.", "Ralph Waldo Emerson"),
    GalleryQuote("Creativity takes courage.", "Henri Matisse"),
    GalleryQuote("An essential aspect of creativity is not being afraid to fail.", "Edwin Land"),

    // ── More Wisdom ──
    GalleryQuote("The journey is the reward.", "Steve Jobs"),
    GalleryQuote("The people who are crazy enough to think they can change the world are the ones who do.", "Steve Jobs"),
    GalleryQuote("Innovation distinguishes between a leader and a follower.", "Steve Jobs"),
    GalleryQuote("Design is not just what it looks like and feels like. Design is how it works.", "Steve Jobs"),
    GalleryQuote("Quality is more important than quantity. One home run is much better than two doubles.", "Steve Jobs"),
    GalleryQuote("Life is either a daring adventure or nothing at all.", "Helen Keller"),
    GalleryQuote("The best and most beautiful things in the world cannot be seen or even touched; they must be felt with the heart.", "Helen Keller"),
    GalleryQuote("Although the world is full of suffering, it is also full of the overcoming of it.", "Helen Keller"),
    GalleryQuote("Optimism is the faith that leads to achievement.", "Helen Keller"),
    GalleryQuote("Alone we can do so little; together we can do so much.", "Helen Keller"),
    GalleryQuote("What you get by achieving your goals is not as important as what you become by achieving your goals.", "Zig Ziglar"),
    GalleryQuote("You don't have to be great to start, but you have to start to be great.", "Zig Ziglar"),
    GalleryQuote("It's not what happens to you, but how you react to it that matters.", "Epictetus"),
    GalleryQuote("Wealth consists not in having great possessions, but in having few wants.", "Epictetus"),
    GalleryQuote("He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.", "Epictetus"),
    GalleryQuote("We have two ears and one mouth so that we can listen twice as much as we speak.", "Epictetus"),
    GalleryQuote("The happiness of your life depends upon the quality of your thoughts.", "Marcus Aurelius"),
    GalleryQuote("You have power over your mind, not outside events. Realize this, and you will find strength.", "Marcus Aurelius"),
    GalleryQuote("The best revenge is to be unlike him who performed the injury.", "Marcus Aurelius"),
    GalleryQuote("Waste no more time arguing about what a good man should be. Be one.", "Marcus Aurelius"),
    GalleryQuote("Accept the things to which fate binds you, and love the people with whom fate brings you together.", "Marcus Aurelius"),
    GalleryQuote("When you arise in the morning, think of what a precious privilege it is to be alive.", "Marcus Aurelius"),
    GalleryQuote("Dwell on the beauty of life. Watch the stars, and see yourself running with them.", "Marcus Aurelius"),
    GalleryQuote("The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.", "Marcus Aurelius"),
    GalleryQuote("Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", "Marcus Aurelius"),
    GalleryQuote("Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", "Marcus Aurelius"),
    GalleryQuote("If it is not right, do not do it; if it is not true, do not say it.", "Marcus Aurelius"),
    GalleryQuote("The soul becomes dyed with the color of its thoughts.", "Marcus Aurelius"),
    GalleryQuote("Wherever you go, go with all your heart.", "Confucius"),
    GalleryQuote("It is better to be a failure at something you love than a success at something you hate.", "George Burns"),
    GalleryQuote("The biggest risk is not taking any risk.", "Mark Zuckerberg"),
    GalleryQuote("Done is better than perfect.", "Sheryl Sandberg"),
    GalleryQuote("Comparison is the thief of joy.", "Theodore Roosevelt"),
    GalleryQuote("Do what you can, with what you have, where you are.", "Theodore Roosevelt"),
    GalleryQuote("Believe you can and you're halfway there.", "Theodore Roosevelt"),
    GalleryQuote("Far and away the best prize that life has to offer is the chance to work hard at work worth doing.", "Theodore Roosevelt"),
    GalleryQuote("Nothing in the world can take the place of persistence.", "Calvin Coolidge"),
    GalleryQuote("The secret of getting ahead is getting started.", "Mark Twain"),
    GalleryQuote("Kind words can be short and easy to speak, but their echoes are truly endless.", "Mother Teresa"),
    GalleryQuote("Spread love everywhere you go. Let no one ever come to you without leaving happier.", "Mother Teresa"),
    GalleryQuote("I can be changed by what happens to me. But I refuse to be reduced by it.", "Maya Angelou"),
    GalleryQuote("People will forget what you said, people will forget what you did, but people will never forget how you made them feel.", "Maya Angelou"),
    GalleryQuote("There is no greater agony than bearing an untold story inside you.", "Maya Angelou"),
    GalleryQuote("If you don't like something, change it. If you can't change it, change your attitude.", "Maya Angelou"),
    GalleryQuote("We may encounter many defeats but we must not be defeated.", "Maya Angelou"),
    GalleryQuote("Still I rise.", "Maya Angelou"),
    GalleryQuote("A person's a person, no matter how small.", "Dr. Seuss"),
    GalleryQuote("Don't cry because it's over, smile because it happened.", "Dr. Seuss"),
    GalleryQuote("You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", "Dr. Seuss"),
    GalleryQuote("Why fit in when you were born to stand out?", "Dr. Seuss"),
    GalleryQuote("Today you are You, that is truer than true. There is no one alive who is Youer than You.", "Dr. Seuss"),
    GalleryQuote("The more that you read, the more things you will know.", "Dr. Seuss"),
    GalleryQuote("Unless someone like you cares a whole awful lot, nothing is going to get better. It's not.", "Dr. Seuss")
)

/**
 * 根据当前系统语言返回对应的格言池。
 * 中文环境返回中文格言，其他语言返回英文格言。
 */
fun getQuotesForLocale(locale: Locale = Locale.getDefault()): List<GalleryQuote> {
    val language = locale.language
    return if (language == "zh") chineseQuotes else englishQuotes
}

/**
 * 从对应语言池中随机取一句格言。
 */
fun getRandomQuoteForLocale(locale: Locale = Locale.getDefault()): GalleryQuote {
    val pool = getQuotesForLocale(locale)
    return pool[kotlin.random.Random.nextInt(pool.size)]
}
